name = "MyFirstPackage"
uuid = "54c9e41f-6bfa-4cfe-81ba-52d6b24badda"
authors = ["1aluo1"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
